In [1]:
import torch
from mpmath import arange
from torch import dtype

print("Hello World")

Hello World


In [2]:
# pip install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu

In [3]:
import torch

if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print ("MPS device is available:", x)
else:
    print ("MPS device not found.")



MPS device is available: tensor([1.], device='mps:0')


In [4]:
import torch

if torch.backends.mps.is_available():
    device = torch.device("mps")
    print("Using MPS (Metal Performance Shaders) for GPU acceleration")
else:
    device = torch.device("cpu")
    print("MPS not available, falling back to CPU")

Using MPS (Metal Performance Shaders) for GPU acceleration


In [5]:
import torch
import time

def check_pytorch_device():
    """
    Checks if PyTorch is configured to use the GPU (MPS) or CPU,
    and performs a simple tensor operation to demonstrate.
    """

    # 1. Determine the device to use
    if torch.backends.mps.is_available():
        device = torch.device("mps")
        print("MPS (Metal Performance Shaders) backend is available.")
        print("Using GPU for computations.")
    else:
        device = torch.device("cpu")
        print("MPS backend not available.")
        print("Using CPU for computations.")

    # 2. Perform a sample tensor operation on the chosen device
    try:
        # Create tensors on the determined device
        tensor_a = torch.randn(1000, 1000, device=device)
        tensor_b = torch.randn(1000, 1000, device=device)

        # Perform a matrix multiplication
        start_time = time.time()
        result = torch.matmul(tensor_a, tensor_b)
        end_time = time.time()

        print(f"\nPerformed a 1000x1000 matrix multiplication on {device.type}.")
        print(f"Time taken: {end_time - start_time:.4f} seconds.")
        print(f"Result device: {result.device}")

        # You can add more complex operations here to test further
        # For example, create a simple neural network and run a forward pass

    except RuntimeError as e:
        print(f"\nAn error occurred during tensor operations: {e}")
        print("This might indicate issues with your PyTorch/MPS setup.")
        print("Double-check your PyTorch installation and environment configuration.")

if __name__ == "__main__":
    check_pytorch_device()



MPS (Metal Performance Shaders) backend is available.
Using GPU for computations.

Performed a 1000x1000 matrix multiplication on mps.
Time taken: 0.0045 seconds.
Result device: mps:0


In [6]:
import torch
if torch.backends.mps.is_available():
    device = torch.device("mps")
    print("Using MPS (Metal Performance Shaders) backend.")
# Allocate some tensors to demonstrate memory usage
    x = torch.randn(1000, 1000, device=device)
    y = torch.randn(1000, 1000, device=device)
    print(f"Current allocated memory: {torch.mps.driver_allocated_memory() / (10242):.2f} MB")
    print(f"Current reserved memory: {torch.mps.current_allocated_memory() / (10242):.2f} MB")
else:
    print("MPS backend not available.")

Using MPS (Metal Performance Shaders) backend.
Current allocated memory: 5160.59 MB
Current reserved memory: 781.10 MB


In [7]:
print(torch.__version__)

2.9.0.dev20250813


In [8]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [10]:
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [11]:
vector.shape

torch.Size([3])

In [12]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
matrix.shape

torch.Size([2, 3])

In [14]:
tensors = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
tensors

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
tensors.shape

torch.Size([1, 3, 3])

In [16]:
tensors.ndim

3

In [17]:
tensors = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensors

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])

In [18]:
tensors.shape,tensors.ndim

(torch.Size([3, 2, 3]), 3)

In [19]:
random_temsor = torch.randn(3,4)

In [20]:
random_temsor

tensor([[ 0.0134, -0.7032,  0.7596,  0.4736],
        [-0.3888,  1.3041, -0.1236,  0.0691],
        [-0.2939,  0.9703, -0.5888, -2.2722]])

In [21]:
zeros =torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones =torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
onetoten = torch.arange(start=1,end=11,step=1)
onetoten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
zeroes = torch.zeros_like(input=onetoten)
zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
float32 = torch.tensor([1.0,2.0,3.0],dtype=None,device=None,requires_grad=False)
float32.dtype
# even dtype is given ,default is float

torch.float32

In [27]:
print(f"{float32.device}")

cpu


In [28]:
tensor = torch.tensor([1,2,3])

In [29]:
tensor+10

tensor([11, 12, 13])

In [30]:
tensor*10

tensor([10, 20, 30])

In [31]:
tensor-10

tensor([-9, -8, -7])

In [32]:
#inbuilt functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [33]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [34]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [35]:
torch.pow(tensor,2)

tensor([1, 4, 9])

In [36]:
#marix multiplication,dot product of matrixes (@)
torch.matmul(tensor,tensor)

tensor(14)

In [37]:
tensor@tensor

tensor(14)

In [38]:
x = torch.arange(0,100,10)
x.dtype

torch.int64

In [39]:
torch.min(x)

tensor(0)

In [40]:
torch.max(x)

tensor(90)

In [41]:
torch.mean(x.type(torch.float32))
#this may give datatype erroe bcz x is int,so convert it into float

tensor(45.)

In [42]:
torch.sum(x)

tensor(450)

In [43]:
x.argmin()

tensor(0)

In [44]:
x[0]

tensor(0)

In [45]:
x.argmax()

tensor(9)

In [46]:
import torch

In [47]:
x = torch.arange(1,10)

In [48]:
xreshaped = x.reshape(9,1)
xreshaped.shape

torch.Size([9, 1])

In [49]:
z = x.view(1,9)
z,z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [50]:
z[:,0]=5
z,x
#change in z will change the x as well

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [51]:
xstacked = torch.stack([x,x,x,x],dim=1)

In [52]:
xstacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [53]:
xreshaped.squeeze()

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
xreshaped.squeeze().shape

torch.Size([9])

In [55]:
xsqueezed = xreshaped.squeeze()

In [56]:
xsqueezed.shape

torch.Size([9])

In [57]:
xunsq = xsqueezed.unsqueeze(dim=0)

In [59]:
xunsq.shape

torch.Size([1, 9])

In [64]:
xoriginal = torch.rand(size=(224,224,3))
xoriginal.shape

torch.Size([224, 224, 3])

In [65]:
xpermuted = xoriginal.permute(2,0,1)
#shifts axis
xpermuted.shape

torch.Size([3, 224, 224])

In [63]:
xoriginal

tensor([[[0.5542, 0.0271, 0.7929],
         [0.2724, 0.9363, 0.6718],
         [0.5663, 0.0972, 0.5152],
         ...,
         [0.3046, 0.0301, 0.5047],
         [0.8057, 0.1802, 0.8501],
         [0.2199, 0.2751, 0.1492]],

        [[0.9298, 0.8194, 0.2173],
         [0.3682, 0.1780, 0.9036],
         [0.3811, 0.3227, 0.3859],
         ...,
         [0.2396, 0.6984, 0.1021],
         [0.1405, 0.5871, 0.3972],
         [0.4169, 0.5379, 0.9056]],

        [[0.2243, 0.3559, 0.8445],
         [0.0319, 0.8556, 0.3692],
         [0.8651, 0.9809, 0.9560],
         ...,
         [0.4516, 0.9294, 0.4657],
         [0.1655, 0.5453, 0.0990],
         [0.3286, 0.7178, 0.9399]],

        ...,

        [[0.4873, 0.7577, 0.9033],
         [0.5388, 0.7104, 0.4445],
         [0.7928, 0.5753, 0.5983],
         ...,
         [0.6190, 0.4798, 0.6260],
         [0.8234, 0.2321, 0.9343],
         [0.3219, 0.3137, 0.4392]],

        [[0.2237, 0.7921, 0.7298],
         [0.5041, 0.0814, 0.8610],
         [0.

In [62]:
xpermuted

tensor([[[0.5542, 0.2724, 0.5663,  ..., 0.3046, 0.8057, 0.2199],
         [0.9298, 0.3682, 0.3811,  ..., 0.2396, 0.1405, 0.4169],
         [0.2243, 0.0319, 0.8651,  ..., 0.4516, 0.1655, 0.3286],
         ...,
         [0.4873, 0.5388, 0.7928,  ..., 0.6190, 0.8234, 0.3219],
         [0.2237, 0.5041, 0.8481,  ..., 0.4306, 0.7345, 0.0034],
         [0.8794, 0.1915, 0.3747,  ..., 0.3280, 0.3143, 0.7443]],

        [[0.0271, 0.9363, 0.0972,  ..., 0.0301, 0.1802, 0.2751],
         [0.8194, 0.1780, 0.3227,  ..., 0.6984, 0.5871, 0.5379],
         [0.3559, 0.8556, 0.9809,  ..., 0.9294, 0.5453, 0.7178],
         ...,
         [0.7577, 0.7104, 0.5753,  ..., 0.4798, 0.2321, 0.3137],
         [0.7921, 0.0814, 0.7300,  ..., 0.1073, 0.5864, 0.5943],
         [0.6626, 0.6728, 0.3427,  ..., 0.3830, 0.9204, 0.9710]],

        [[0.7929, 0.6718, 0.5152,  ..., 0.5047, 0.8501, 0.1492],
         [0.2173, 0.9036, 0.3859,  ..., 0.1021, 0.3972, 0.9056],
         [0.8445, 0.3692, 0.9560,  ..., 0.4657, 0.0990, 0.

In [66]:
x = torch.arange(1,10).reshape(1,3,3)

In [67]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [68]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [69]:
x[0][0]

tensor([1, 2, 3])

In [70]:
x[0][0][0]

tensor(1)

In [82]:
import torch
import numpy as np
#numpy to tensor

In [72]:
array = np.arange(1.,8.);

In [76]:
tensor = torch.from_numpy(array)

In [77]:
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [78]:
array = array + 1

In [81]:
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [83]:
#tensor to numpy
tensor = torch.ones(7)
numpytesor = tensor.numpy()
numpytesor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [85]:
import torch

randomtensorA = torch.rand(3,4)
randomtensorB = torch.rand(3,4)

print(randomtensorA)
print(randomtensorB)
print(randomtensorA==randomtensorB)

tensor([[0.9295, 0.0281, 0.1148, 0.6137],
        [0.1310, 0.1693, 0.7331, 0.7882],
        [0.6254, 0.5574, 0.7379, 0.1777]])
tensor([[0.6642, 0.9108, 0.8658, 0.7383],
        [0.8095, 0.0644, 0.0384, 0.7230],
        [0.1931, 0.2104, 0.0615, 0.8684]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [87]:
RANDOMSEED = 42
torch.manual_seed(RANDOMSEED)
randomC = torch.rand(3,4)
torch.manual_seed(RANDOMSEED)
randomD = torch.rand(3,4)

In [88]:
randomC,randomD

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [90]:
#accessing GPU (mps) for training
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'mps'

In [91]:
torch.cuda.is_available()

False

In [95]:
    import torch

    if torch.backends.mps.is_available():
        device = torch.device("mps")
        print("Using Apple Silicon MPS GPU.")
    else:
        device = torch.device("cpu")
        print("Using CPU.")


Using Apple Silicon MPS GPU.


In [103]:
tensor = torch.tensor([1,2,3])

In [104]:
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [113]:
#moving tensors to GPU(mps)
tensor_to_gpu = tensor.to(device)

In [114]:
print(tensor_to_gpu.device)

mps:0


In [115]:
#numpy needs cpu to work,so we should go back to cpu and then we need to use numpy
# tensor.numpy()

In [116]:
tensor_to_cpu = tensor_to_gpu.cpu()

In [117]:
tensor_to_cpu.numpy()

array([1, 2, 3])

In [118]:
print(tensor_to_cpu.device)

cpu
